### PR TITLE
CMake: Fix (lack of) detection of aarch64 cpus as ARM processors.

### PR DESCRIPTION
**Pull request by teknoman117**
- Added aarch64 to the list of processors classified as ARM processors.
- Renamed OPUS_MAY_SUPPORT_NEON to OPUS_MAY_HAVE_NEON as the latter is the name used in the rest of the build system.
- Changed the default of OPUS_MAY_HAVE_NEON to OFF as it requires runtime cpu feature detection, which isn't currently implemented for ARM.

### CODE REVIEW

**Comment by xnorpx** [comment]
@teknoman117 

#  if defined(OPUS_ARM_MAY_HAVE_NEON) || defined(OPUS_ARM_MAY_HAVE_NEON_INTR)
        p = strstr(buf, " neon");
        if(p != NULL && (p[5] == ' ' || p[5] == '\n'))
          flags |= OPUS_CPU_ARM_NEON_FLAG;
#  endif

in celt\arm\armcpu.c

not working? (I haven't tested but just wanted to doublecheck)

**Comment by teknoman117** [comment]
@xnorpx , /proc/cpuinfo isn't always accessible to an application, such as on Android. There are some android specific ways of detecting instruction set support.

**Comment by teknoman117** [comment]
@xnorpx also, as for the two specific changes I made: The CMake option for NEON was defined as "OPUS_MAY_SUPPORT_NEON" in opus_config.cmake (https://github.com/xiph/opus/blob/master/opus_config.cmake#L37), however the rest of the build system uses "OPUS_MAY_HAVE_NEON" (https://github.com/xiph/opus/blob/master/CMakeLists.txt#L285).

**Comment by teknoman117** [comment]
@jmvalin and @felicialim, could either of you take a look? This breaks the CMake for arm64 (I tried in an arm64 container and on Android).

**Comment by xnorpx** [comment]
I think it's fair to turn it off I never tested it runtime on android, my initial thought was to test the neon dispatch at work but priorities got changed and never got around to it.

**Comment by xnorpx** [comment]
You can create pull request here https://github.com/xnorpx/opus and I send it over to jmvalin in my next cmake patch update if they don't merge it from here.

**Comment by teknoman117** [comment]
@xnorpx I have created PR's on your fork.

**Comment by teknoman117** [comment]
closing due to working on this on the xnorpx fork (I'm assuming they are the CMake build system maintainer)

**Pull request closed without merging**
