### PR TITLE
meson: Fix reporting of cpu family if intrinsics not supported

### PR DESCRIPTION
**Pull request by dougnazar**
Signed-off-by: Doug Nazar <nazard@nazar.ca>

### CODE REVIEW

**Comment by xnorpx** [comment]
@tp-m something you want into Meson before next release?

**Comment by tp-m** [comment]
Thanks for the reminder.

The MR seems fine to me, it makes the error message a bit clearer I think.

It doesn't seem to change anything other than the error message afaict, so should be safe to merge.

**Comment by xnorpx** [comment]
@tp-m do you have time to bring it over to gitlab? (I can do it if you are swamped)

**Comment by tp-m** [comment]
Oh sure, didn't notice this was in the wrong place.

Might be worth to set up a bot that closes MRs on github with a polite message to please re-submit them in gitlab :)

**Comment by tp-m** [comment]
-> https://gitlab.xiph.org/xiph/opus/-/merge_requests/41

**Comment by xnorpx** [comment]
This has been merged and can be closed @mark4o or @dougnazar

**Pull request closed without merging**
