### PR TITLE
fix arm asm meson source build

### LINKED ISSUE #295: Meson builds with arm “--enable-fixed-point” fail with invalid meson syntax
Build fails with:

../celt/meson.build:49:25: ERROR: configure_file keyword argument "output" Output 'arm/armopts.s' must not contain a path segment.

https://github.com/xiph/opus/blob/9fc8fc4cf432640f284113ba502ee027268b0d9f/celt/meson.build#L50

### LINKED ISSUE #316: arm build with meson fails with: Unknown variable "opus_arm_may_have_dotprod"
When building arm32 with meson the build fails with the following error.

```
BUILD      opus (target)
    TOOLCHAIN      meson (auto-detect)
Executing (target): meson setup --prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --libdir=/usr/lib --libexecdir=/usr/lib --localstatedir=/var --buildtype=plain -Dstrip=true --cross-file=/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RPi2.arm-12.0-devel/build/opus-23d4b31de15a723716f9fde5ec736773f2e1aa2e/.armv7ve-libreelec-linux-gnueabihf/meson.conf -Ddefault_library=static -Ddocs=disabled -Dextra-programs=disabled -Dtests=disabled -Dfixed-point=true /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RPi2.arm-12.0-devel/build/opus-23d4b31de15a723716f9fde5ec736773f2e1aa2e
The Meson build system
Version: 1.3.2
Source dir: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RPi2.arm-12.0-devel/build/opus-23d4b31de15a723716f9fde5ec736773f2e1aa2e
Build dir: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RPi2.arm-12.0-devel/build/opus-23d4b31de15a723716f9fde5ec736773f2e1aa2e/.armv7ve-libreelec-linux-gnueabihf
Build type: cross build
Project name: opus
Project version: 1.4-git-23d4b31
C compiler for the host machine: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RPi2.arm-12.0-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabihf-gcc (gcc 13.2.0 "armv7ve-libreelec-linux-gnueabihf-gcc-13.2.0 (GCC) 13.2.0")
C linker for the host machine: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RPi2.arm-12.0-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabihf-gcc ld.gold 2.42
C compiler for the build machine: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RPi2.arm-12.0-devel/toolchain/bin/host-gcc (gcc 13.2.0 "gcc (Ubuntu 13.2.0-9ubuntu1) 13.2.0")
C linker for the build machine: /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RPi2.arm-12.0-devel/toolchain/bin/host-gcc ld.bfd 2.41.50.20231227
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: arm
Host machine cpu: armv7ve
Target machine cpu family: arm
Target machine cpu: armv7ve
Compiler for C supports arguments -fvisibility=hidden: YES 
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -fstack-protector-strong: YES 
Library m found: YES
Checking for function "lrintf" with dependency -lm: YES 
Checking for function "lrint" with dependency -lm: YES 
Checking for function "__malloc_hook" : NO 
Check usable header "stdint.h" : YES 
Checking if "restrict keyword" compiles: YES 
Checking if "C99 variable-size arrays" compiles: YES 
Checking if "compiler supports gcc-style inline assembly" compiles: NO 
Program perl found: YES (/usr/bin/perl)
Message: Trying to force-enable armv5e EDSP instructions...
Checking if "Assembler supports EDSP instructions on ARM (forced)" compiles: NO 
Message: Trying to force-enable ARMv6 media instructions...
Checking if "Assembler supports ARMv6 media instructions on ARM (forced)" compiles: NO 
Message: Trying to force-enable NEON instructions...
Checking if "Assembler supports NEON instructions on ARM (forced)" compiles: NO 

../meson.build:322:9: ERROR: Unknown variable "opus_arm_may_have_dotprod".

A full log can be found at /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RPi2.arm-12.0-devel/build/opus-23d4b31de15a723716f9fde5ec736773f2e1aa2e/.armv7ve-libreelec-linux-gnueabihf/meson-logs/meson-log.txt
```
Build on aarch64 completes successfully with:
``` 
Checking if "C99 variable-size arrays" compiles: YES 
Checking if "compiler supports ARMv7/AArch64 NEON intrinsics" : links: YES 
Checking if "compiler supports AArch64 NEON intrinsics" : links: YES 
Checking if "compiler supports AArch64 DOTPROD intrinsics" : links: NO 
Checking if "compiler supports AArch64 DOTPROD intrinsics with -march=armv8.2-a+dotprod" : links: YES 
Configuring config.h using configuration
```

### PR DESCRIPTION
**Pull request by heitbaum**
meson does mot support output with paths; add a meson.build file in the arm directory. The output files were being incorrectly placed in the celt/ directory.

Program arm/arm2gnu.pl found: YES (/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-12.0-devel/build/opus-v1.5.1/celt/arm/arm2gnu.pl) Configuring celt_pitch_xcorr_arm-gnu.S with command

../celt/meson.build:51:25: ERROR: configure_file keyword argument "output" Output 'arm/armopts.s' must not contain a path segment.

before:
celt/celt_pitch_xcorr_arm-gnu.S

after:
celt/arm/celt_pitch_xcorr_arm-gnu.S
celt/arm/armopts.s
celt/arm/armopts-gnu.S

—-

this patch whilst fixing the meson build failure during the creation of source files and allowing the meson build to progress - still fails on an assembly error.

```
Program perl found: YES (/usr/bin/perl)
Message: Trying to force-enable armv5e EDSP instructions...
Checking if "Assembler supports EDSP instructions on ARM (forced)" compiles: NO 
Message: Trying to force-enable ARMv6 media instructions...
Checking if "Assembler supports ARMv6 media instructions on ARM (forced)" compiles: NO 
Message: Trying to force-enable NEON instructions...
Checking if "Assembler supports NEON instructions on ARM (forced)" compiles: NO 
Fetching value of define "__APPLE__" : (undefined) 
Checking if "compiler supports ARMv7/AArch64 NEON intrinsics" : links: YES 
Checking if "compiler supports AArch64 NEON intrinsics" : links: NO 
Checking if "compiler supports AArch64 NEON intrinsics with -mfpu=neon" : links: NO 
Message: Compiler does not support AArch64 NEON intrinsics
Checking if "compiler supports AArch64 DOTPROD intrinsics" : links: NO 
Checking if "compiler supports AArch64 DOTPROD intrinsics with -march=armv8.2-a+dotprod" : links: NO 
Message: Compiler does not support AArch64 DOTPROD intrinsics
Program arm2gnu.pl found: YES (/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-12.0-devel/build/opus-v1.5.1/celt/arm/arm2gnu.pl)
Configuring celt_pitch_xcorr_arm-gnu.S with command
Configuring armopts.s using configuration
../celt/arm/meson.build:6: WARNING: The variable(s) 'OPUS_ARM_MAY_HAVE_EDSP', 'OPUS_ARM_MAY_HAVE_MEDIA', 'OPUS_ARM_MAY_HAVE_NEON' in the input file 'celt/arm/armopts.s.in' are not present in the given configuration data.
Configuring armopts-gnu.S with command
Configuring config.h using configuration
Configuring opus.pc using configuration
Program doxygen skipped: feature docs disabled
Build targets in project: 7

opus 1.4-git-v1.5.1

  Compiler support
    C99 var arrays                 : YES
    C99 lrintf                     : YES
    Use alloca                     : NO (using C99 variable-size arrays instead)

  Optimizations
    Floating point support         : NO
    Fast float approximations      : NO
    Fixed point debugging          : NO
    Inline assembly optimizations  : none
    External assembly optimizations: none
    Intrinsics optimizations       : ARMv7/AArch64 NEON
    Run-time CPU detection         : not needed

  General configuration
    Custom modes                   : NO
    Assertions                     : NO
    Hardening                      : YES
    Fuzzing                        : NO
    Check ASM                      : NO
    API documentation              : NO
    Extra programs                 : NO
    Tests                          : NO

  User defined options
    Cross files                    : /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-12.0-devel/build/opus-v1.5.1/.armv7ve-libreelec-linux-gnueabihf/meson.conf
    bindir                         : /usr/bin
    buildtype                      : plain
    default_library                : static
    libdir                         : /usr/lib
    libexecdir                     : /usr/lib
    localstatedir                  : /var
    prefix                         : /usr
    sbindir                        : /usr/sbin
    strip                          : true
    sysconfdir                     : /etc
    docs                           : disabled
    extra-programs                 : disabled
    fixed-point                    : true
    tests                          : disabled

Found ninja-1.11.1 at /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-12.0-devel/toolchain/bin/ninja
Executing (target): ninja 
[1/149] Compiling C object celt/libcelt-armasm.a.p/meson-generated_.._arm_armopts-gnu.S.o
FAILED: celt/libcelt-armasm.a.p/meson-generated_.._arm_armopts-gnu.S.o 
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-12.0-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabihf-gcc -Icelt/libcelt-armasm.a.p -Icelt -I../celt -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu99 -DOPUS_BUILD -DHAVE_CONFIG_H -fvisibility=hidden -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -fstack-protector-strong -march=armv7ve -mtune=cortex-a7 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mfloat-abi=hard -mfpu=neon-vfpv4 -Wall -pipe -O2 -fomit-frame-pointer -DNDEBUG -fPIC -DPIC -fPIC -MD -MQ celt/libcelt-armasm.a.p/meson-generated_.._arm_armopts-gnu.S.o -MF celt/libcelt-armasm.a.p/meson-generated_.._arm_armopts-gnu.S.o.d -o celt/libcelt-armasm.a.p/meson-generated_.._arm_armopts-gnu.S.o -c celt/arm/armopts-gnu.S
celt/arm/armopts-gnu.S: Assembler messages:
celt/arm/armopts-gnu.S:30: Error: missing expression
celt/arm/armopts-gnu.S:33: Error: missing expression
celt/arm/armopts-gnu.S:36: Error: missing expression
[2/149] Compiling C object celt/libcelt-armasm.a.p/meson-generated_.._arm_celt_pitch_xcorr_arm-gnu.S.o
FAILED: celt/libcelt-armasm.a.p/meson-generated_.._arm_celt_pitch_xcorr_arm-gnu.S.o 
/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-H3.arm-12.0-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabihf-gcc -Icelt/libcelt-armasm.a.p -Icelt -I../celt -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu99 -DOPUS_BUILD -DHAVE_CONFIG_H -fvisibility=hidden -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -fstack-protector-strong -march=armv7ve -mtune=cortex-a7 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mfloat-abi=hard -mfpu=neon-vfpv4 -Wall -pipe -O2 -fomit-frame-pointer -DNDEBUG -fPIC -DPIC -fPIC -MD -MQ celt/libcelt-armasm.a.p/meson-generated_.._arm_celt_pitch_xcorr_arm-gnu.S.o -MF celt/libcelt-armasm.a.p/meson-generated_.._arm_celt_pitch_xcorr_arm-gnu.S.o.d -o celt/libcelt-armasm.a.p/meson-generated_.._arm_celt_pitch_xcorr_arm-gnu.S.o -c celt/arm/celt_pitch_xcorr_arm-gnu.S
celt/arm/armopts-gnu.S: Assembler messages:
celt/arm/armopts-gnu.S:30: Error: missing expression
celt/arm/armopts-gnu.S:33: Error: missing expression
celt/arm/armopts-gnu.S:36: Error: missing expression
[16/149] Compiling C object celt/libopus-celt.a.p/celt_encoder.c.o
ninja: build stopped: subcommand failed.
```
- Fixes #295
- Fixes #316

### CODE REVIEW

**Comment by jmvalin** [comment]
It would help to understand why meson seems to work in most other cases but not in yours. Any idea?

**Comment by heitbaum** [comment]
The build patch of using `-Dfixed-point=true` on `arm` causes the error.
`-Dfixed-point=false` does not hit this code. I’m guessing that others may not be using this `-D` in their builds.

The failing build command line is:
`Executing (target): meson setup --prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --libdir=/usr/lib --libexecdir=/usr/lib --localstatedir=/var --buildtype=plain -Dstrip=true --cross-file=/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RPi2.arm-12.0-devel/build/opus-v1.5.1/.armv7ve-libreelec-linux-gnueabihf/meson.conf -Ddefault_library=static -Ddocs=disabled -Dextra-programs=disabled -Dtests=disabled -Dfixed-point=true /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RPi2.arm-12.0-devel/build/opus-v1.5.1 `

A successful build command line is:
`Executing (target): meson setup --prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --libdir=/usr/lib --libexecdir=/usr/lib --localstatedir=/var --buildtype=plain -Dstrip=true --cross-file=/var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RPi2.arm-12.0-devel/build/opus-v1.5.1/.armv7ve-libreelec-linux-gnueabihf/meson.conf -Ddefault_library=static -Ddocs=disabled -Dextra-programs=disabled -Dtests=disabled -Dfixed-point=false /var/media/DATA/home-rudi/LibreELEC.kernel11/build.LibreELEC-RPi2.arm-12.0-devel/build/opus-v1.5.1`

**Comment by jmvalin** [comment]
Actually, your "failing build" command (minus the --cross-file=) succeeds for me on my RPi 5 (Raspbian I think). Not sure what's different.

**Comment by heitbaum** [comment]
> Actually, your "failing build" command (minus the --cross-file=) succeeds for me on my RPi 5 (Raspbian I think). Not sure what's different.

Are you targeting 32bit runtime or 64bit runtime?
64bit works fine here. It’s only the 32bit build.

that `arm/armopts.s` line is hard fail in meson (once I found the article - there is lots of discussion about that)

**Comment by heitbaum** [comment]
I have spent some more time on this and fixed a couple more meson.build with asm issues.

there is only 1 remaining error in the meson.build (for this arm32 build)

`../meson.build:322:9: ERROR: Unknown variable "opus_arm_may_have_dotprod".`

If I cheat by using this patch - my full compile is successful. I need to review and understand what this block is doing before I try and fix this. As none of the other builds fail on this line, but I can’t see where it is set in the first place.
```
diff --git a/meson.build b/meson.build
index 56232609..9b14b79e 100644
--- a/meson.build
+++ b/meson.build
@@ -319,6 +319,7 @@ if not opt_asm.disabled()
           rtcd_support += ['NEON']
         endif
       endif
+      opus_arm_may_have_dotprod = false
       if opus_arm_may_have_dotprod
         opus_conf.set('OPUS_ARM_MAY_HAVE_DOTPROD', 1)
         if opus_arm_presume_dotprod
```

**Comment by heitbaum** [comment]
Added the missing assembler dotprod checks.

**Comment by heitbaum** [comment]
- Fixes #295
- Fixes #316

**Comment by jmvalin** [comment]
OK, I think I merged everything. Let me know if I forgot or messed up something

**Comment by heitbaum** [comment]
> OK, I think I merged everything. Let me know if I forgot or messed up something

looks good. I have done a full build - all built correctly.

**Pull request closed without merging**
