### PR TITLE
replace a few WIN32 checks with _WIN32

### PR DESCRIPTION
**Pull request by sezero**
also remove a left-over windows-or-linux check from
within a windows-only case in debug.c.

### CODE REVIEW

**Comment by sezero** [comment]
PING ?

**Comment by jmvalin** [comment]
What's the difference between WIN32 and _WIN32 exactly? (not a Windows user) Also, I'm a bit concerned about the changes to silk/debug.c which is not used by default (so you wouldn't notice if it gets broken).

**Comment by sezero** [comment]
> What's the difference between WIN32 and _WIN32 exactly? (not a Windows user)

`_WIN32` is a compiler define, both for gcc and visual studio. WIN32 w/o the _ prefix
is just a user define. 

> Also, I'm a bit concerned about the changes to silk/debug.c which is not used by
> default (so you wouldn't notice if it gets broken).

And the current situation is confusing (to me, at least..)

**Comment by jmvalin** [comment]
> And the current situation is confusing (to me, at least..)

What's confusing to you?

**Comment by sezero** [comment]
> > And the current situation is confusing (to me, at least..)
> 
> What's confusing to you?

Trying to understand the hidden meaning in duplicated ifdefs where there is none.

**Pull request closed without merging**
