### PR TITLE
Fix CMake install include directory

### PR DESCRIPTION
**Pull request by evpobr**
Install include directory must be `include/opus`, not `include`.

Old path is still here for compatibility.

Related to #164, closes erikd/libsndfile#506.

### CODE REVIEW

**Comment by xnorpx** [comment]
@evpobr can you create pull request here: https://github.com/xnorpx/opus and I send it over with the other patches

**Comment by xnorpx** [comment]
this has been merged

**Comment by xnorpx** [comment]
@evpobr , @rillian  , @mark4o  this has been merged so this PR can be closed

**Comment by rillian** [comment]
Right, this landed in d637b9022. Thanks.

**Pull request closed without merging**
