### PR TITLE
Added test to validate and measure functions from pitch_sse.c

### PR DESCRIPTION
**Pull request by rvelea**
Added test to validate and measure functions from pitch_sse.c

The test measures the performance and output of 
xcorr_kernel_c
dual_inner_prod_simd_c
celt_inner_prod_c
comb_filter_const_c
compared to their SIMD counterparts (for now x86 SSE).

The test displays time and eventual RMS error between C output and SSE.

### CODE REVIEW

**Comment by rvelea** [comment]
This test is part of an effort to port the aforementioned functions from SSE to AVX. 
I used a Linux x64 Haswell machine running Ubuntu.
Here are the runtime values (in ms) for 100 000 iterations:

			Normal C	                SSE		        AVX		SSE / AVX speedup
xcorr_kernel		95.451		41.264		22.841		1.806x
dual_inner_prod	71.897		21.415		16.352		1.309x
celt_inner_prod	70.886		20.302		12.653		1.604x
comb_filter_const	16.108		6.317		3.329		1.897x

**Comment by jmvalin** [comment]
Thanks for the PR. You should have mentioned it on the mailing list or otherwise since I just realized it's there (the github repo is just a mirror). 

I just tried compiling and it failed with:
  CCLD     celt/tests/test_unit_pitch_float
celt/tests/test_unit_pitch_float.o: In function `test_dual_inner_prod':
.../celt/tests/test_unit_pitch_float.c:138: undefined reference to `dual_inner_prod_simd_c'
collect2: error: ld returned 1 exit status

**Comment by rillian** [comment]
@rvelea Are you still working on this?

**Comment by jmvalin** [comment]
No response, closing for now. Feel free to re-open if you have a follow-up.

**Pull request closed without merging**
