### PR TITLE
Proper detection of _mm_cvtss_si32 for MS compiler

### PR DESCRIPTION
**Pull request by pps83**
_mm_cvtss_si32 is available starting from SSE

### CODE REVIEW

**Comment by jmvalin** [comment]
I don't think the defined(_M_IX86_FP) part is needed since _M_IX86_FP will automatically expand to 0 if undefined. Also why the explicit AVX test? Are there cases when it triggers without the other ones being defined?

**Comment by pps83** [comment]
I agree, kind of strange, but I took the check as-is from win32/config

**Comment by jmvalin** [comment]
Merged the first part (_mm_cvtss_si32) for 1.3. I'll handle the rest in a future release.

**Comment by jmvalin** [comment]
Rest of the patch merged in master

**Pull request closed without merging**
